# Generated by Django 5.1.6 on 2025-03-02 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "webapp",
            "0005_rename_can_assign_permissions_customuser_can_modify_groups_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leading_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
